#!/usr/bin/env python
import sys, os.path
install_path = sys.argv[1]
target_platform = sys.argv[2]
if target_platform != "iPhone": sys.exit()
mod_path = os.path.join('.', 'Assets', 'Editor', 'NeatPlug', 'Common', 'lib')
sys.path.append(mod_path)
from mod_pbxproj import XcodeProject
project_path = os.path.join(install_path, 'Unity-iPhone.xcodeproj', 'project.pbxproj')
project = XcodeProject.Load(project_path)
project.add_other_ldflags('-ObjC')
project.add_file_if_doesnt_exist('System/Library/Frameworks/StoreKit.framework', tree='SDKROOT')
if project.modified: project.backup()
project.saveFormat3_2()
