import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { OrganizationGame } from '@/lib/models/OrganizationGame';
import { GeneratedGame } from '@/lib/models/GeneratedGame';

export async function GET(req: Request) {
    try {
        const cookieStore = await cookies();
        const orgId = cookieStore.get('user_id')?.value;

        if (!orgId) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const orgGames = await OrganizationGame.findAll({
            where: { organization_id: orgId },
            include: [{ model: GeneratedGame }]
        });

        // Fetch all games generated by this organization
        const allGames = await GeneratedGame.findAll({
            where: { user_id: orgId },
            order: [['created_at', 'DESC']]
        });

        // Merge state
        const gamesWithStatus = allGames.map(game => {
            const orgGame = orgGames.find(og => og.generated_game_id === game.id);
            return {
                ...game.toJSON(),
                is_active: orgGame ? orgGame.is_active : false,
                associated_skill: orgGame ? orgGame.associated_skill : null,
                associated_mood: orgGame ? orgGame.associated_mood : null,
                organization_game_id: orgGame ? orgGame.id : null
            };
        });

        return NextResponse.json({ success: true, games: gamesWithStatus });
    } catch (error: any) {
        console.error("Fetch Org Games Error:", error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}

export async function POST(req: Request) {
    try {
        const cookieStore = await cookies();
        const orgId = cookieStore.get('user_id')?.value;

        if (!orgId) {
            return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
        }

        const { generated_game_id, is_active, associated_skill, associated_mood } = await req.json();

        if (!generated_game_id) {
            return NextResponse.json({ error: 'Game ID is required' }, { status: 400 });
        }

        const [orgGame, created] = await OrganizationGame.findOrCreate({
            where: { organization_id: orgId, generated_game_id },
            defaults: { is_active, associated_skill, associated_mood }
        });

        if (!created) {
            if (is_active !== undefined) orgGame.is_active = is_active;
            if (associated_skill !== undefined) orgGame.associated_skill = associated_skill;
            if (associated_mood !== undefined) orgGame.associated_mood = associated_mood;
            await orgGame.save();
        }

        return NextResponse.json({ success: true, game: orgGame });
    } catch (error: any) {
        console.error("Toggle Org Game Error:", error);
        return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
    }
}
