#!/usr/bin/env python3
"""Regenerate lib/gameArtMotion.ts from Thomas's Portal v2 export.

The animated game-card backgrounds are generated on the design side
(Reference/tools/pattern-motion-lab/build_portal.py) into js/pattern-motion.js.
This script lifts its two tables, PATTERNS and ART, into a typed module, and
adds the game-name -> art-file mapping read off the export's games.html.

    B=https://skillprint.mexicacollection.com/skillprint/skillprint-portal-v2
    curl -s $B/js/pattern-motion.js -o /tmp/pattern-motion.js
    curl -s "$B/games.html?state=complete" -o /tmp/games.html
    curl -s $B/css/pattern-motion.css -o app/pattern-motion.css
    python3 scripts/build-pattern-motion.py /tmp/pattern-motion.js /tmp/games.html

Then fetch any new $B/assets/images/games/icon-layers/<file> the ART table names
into public/assets/images/games/icon-layers/.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'lib' / 'gameArtMotion.ts'


def js_object(src: str, name: str) -> dict:
    start = src.index(f'var {name} = ') + len(f'var {name} = ')
    end = src.index('};', start) + 1
    return json.loads(src[start:end])


def compact(name: str) -> str:
    return re.sub(r'[^a-z0-9]', '', name.lower())


def main(pattern_js: str, games_html: str) -> None:
    src = Path(pattern_js).read_text()
    patterns = js_object(src, 'PATTERNS')
    art = js_object(src, 'ART')

    bodies = {}
    for key, svg in patterns.items():
        head = re.match(r'<svg[^>]*>', svg).group(0)
        assert 'viewBox="0 0 380 210"' in head and 'xMidYMid slice' in head, key
        bodies[key] = svg[len(head):-len('</svg>')]

    names = {}
    for card in Path(games_html).read_text().split('<article ')[1:]:
        title = re.search(r'<h3>(?:<a[^>]*>)?([^<]+)', card)
        file = re.search(r'icon-layers/([^"]+\.svg)', card)
        if title and file and file.group(1) in art:
            names[compact(title.group(1).replace('&#39;', "'"))] = file.group(1)

    lines = [
        '// Generated by scripts/build-pattern-motion.py from the Portal v2 export',
        '// (js/pattern-motion.js and games.html). Do not hand-edit; regenerate.',
        '',
        "export type PatternTone = 'lime' | 'green' | 'blue' | 'violet' | 'magenta' | 'pink' | 'orange' | 'panel-navy';",
        '',
        '/** Inner markup of each pattern, drawn in a 380 x 210 canvas. */',
        'export const PATTERNS: Record<string, string> = ' + json.dumps(bodies, indent=1) + ';',
        '',
        '/** Icon-layer file -> [pattern, tone]. */',
        'export const ART: Record<string, [string, PatternTone]> = ' + json.dumps(art, indent=1) + ';',
        '',
        '/** Game name, lowercased with everything but letters and digits removed -> icon-layer file. */',
        'export const ART_BY_NAME: Record<string, string> = ' + json.dumps(dict(sorted(names.items())), indent=1) + ';',
        '',
    ]
    OUT.write_text('\n'.join(lines))
    print(f'{OUT.relative_to(ROOT)}: {len(bodies)} patterns, {len(art)} art files, {len(names)} names')


if __name__ == '__main__':
    main(*sys.argv[1:3])
